name: Build and deploy ASP.Net Core app to Azure Web App - sonic221

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore NuGet packages for Presentation project
        run: dotnet restore ./Presentation/Presentation.csproj

      - name: Build the Presentation project
        run: dotnet build ./Presentation/Presentation.csproj --configuration Release

      - name: Publish the Presentation project
        run: dotnet publish ./Presentation/Presentation.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sonic221'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/myapp
